FROM node:12.13.0 as frontend

COPY package.json /srv/
COPY package-lock.json /srv/
RUN cd /srv && npm install
COPY reactjs/ /srv/reactjs/
COPY webpack.dev.config.js /srv/
COPY .babelrc /srv/
RUN cd /srv && npx webpack --config /srv/webpack.dev.config.js
RUN ls /srv

FROM python:3.7.4 as backend
COPY requirements.txt /srv/
RUN cd /srv && pip install -r requirements.txt
RUN cd /srv && pip install uwsgi
COPY --from=frontend /srv/static /srv/static
COPY --from=frontend /srv/webpack-stats.json /srv
COPY real_good/ /srv/real_good/
RUN cd /srv && python real_good/manage.py collectstatic --noinput
RUN cd /srv && python real_good/manage.py makemigrations --noinput
EXPOSE 80
#CMD ["python", "/srv/real_good/manage.py", "runserver", "0.0.0.0:80"]
CMD ["uwsgi", "--chdir", "/srv/real_good", "--module", "real_good.wsgi:application", "--http-socket", "0.0.0.0:80", "--static-map", "/static=../collected_static"]
