version: '3'
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:80"
    environment:
      DATABASE: "postgres://ramanujan:fractions@db:5432/rg"
    links:
      - db
    depends_on:
      - db
  db:
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_USER: 'ramanujan'
      POSTGRES_PASSWORD: 'fractions'
      POSTGRES_DB: 'rg'
      DEBUG: 'true'
